### ISSUE TITLE
Where is "config.h"?

### ISSUE THREAD

**Issue by tleger1958** [evanbowman/Blind-Jump#12]
Hello, and congratulations for your amazing work!

I try to compile from sources the project. But, in the files "main.cpp" and "ResourcePath.hpp", there is this include: 
`#include "config.h"`

And I don’t find this file...

Where is the problem?

Thank you.

**Comment by evanbowman** [comment]
Thanks!

The cmake script is supposed to take a file called config.h.in in the build directory, and write some version strings into it during configuration (https://github.com/evanbowman/blind-jump/blob/master/build/CMakeLists.txt#L17). I don't know why it wouldn't be working, but if you're able to list your build steps I might notice something that may have gone wrong.

**Comment by evanbowman** [comment]
You ran cmake from the build directory, right? It could also be that you ran cmake from a higher directory somehow and the glob-recurse is still picking up all the source files but writing the config.h into the wrong location (but that's all just speculation, if your in a terminal, `cd` up a few directories and see if you can `find . -name "config.h"` and it's being written but somewhere we don't expect) .

**Comment by tleger1958** [comment]
Thank you so munch for your quick answer!

I realize that I should have done some research on the "configure_file()" function...
On Clion, "configure_file()" writes output to a "cmake-build-debug" folder. It's a stupid mistake on my part not to realize it.

On the other hand, I still have problems... Maybe I'm a noob! In the file "soundController. hpp", there is this structure:

`structure runningData {... };`

and it's a problem:

```
blind-jump/src/src/soundController.hpp: 46:29: error: declaration of' std:: deque<runningData> SoundController:: runningData'[-fpermissive])
     std::: deque<runningData> runningData;

blind-jump/src/src/soundController.hpp: 20:8: error: changes meaning of' runningData' from' struct runningData'[-fpermissive]).
 structure runningData { runData
```

The flag -fpermissive must be used to solve this problem.

But once that's done, I still have a problem... A library problem. It seems that your Cmake configuration file doesn't allow to link SFML... "indefinite reference to ’sf:: ....’"

Once I have successfully linked SFML, here is another problem: 
`reference to the undefined symbol "pthread_create@@@GLIBC_2.2.5".`

And by adding -pthread to CMAKE_CXX_FLAGS, **it's work!!!!**

Your game is really cool, really very well done, and I'm really happy that you put the code on Github, so that everyone can try to analyze and understand it.
